### ISSUE TITLE
License of hogments

### ISSUE THREAD

**Issue by regit** [yaunj/hogments#1]
Hello,

I'm planning to reuse some code of hogments for an interface. Could you specify what is the license of this project ?

Thanks for your work!

**Comment by yaunj** [comment]
Since Pygments is BSD licensed, I guess that makes sense for hogments as
well. I'll add some clarification in the repo later.

I haven't really used it much, but I'll be happy to hear from you if you
have improvements. What interface are you building?

Best regards
Rune Hammersland

**Comment by regit** [comment]
Hi,

Thanks for the fast response. 

FYI, I'm working on https://github.com/StamusNetworks/scirius. As it is a suricata ruleset management system, I will use hogments code as a base for suricata syntax.

**Comment by yaunj** [comment]
Licensing information is added in the repository now.

Regards
Rune Hammersland

On Sun, Aug 17, 2014 at 10:49 PM, Eric Leblond notifications@github.com
wrote:

> Hi,
> 
> Thanks for the fast response.
> 
> FYI, I'm working on https://github.com/StamusNetworks/scirius. As it is a
> suricata ruleset management system, I will use hogments code as a base for
> suricata syntax.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yaunj/hogments/issues/1#issuecomment-52434484.

## 

mvh
Rune Hammersland
